config/routes.rb
Rails.application.routes.draw do
  get 'login' => 'user_sessions#new', as: :login
  get 'logout' => 'user_sessions#destroy', as: :logout

  resource :user_sessions
  resources :users
  
  root 'users#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user

  private
  
  def current_user_session
    return @current_user_session if defined?(@current_user_session)
    @current_user_session = UserSession.find
  end

  def current_user
    @current_user = current_user_session && current_user_session.record
  end
  
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    @user_session = UserSession.new
  end
  
  def create
    session_params = params.require(:user_session).permit!
    @user_session = UserSession.new(session_params)
    if @user_session.save
      redirect_to root_url, notice: 'Successfully logged in.'
    else
      render :new
    end
  end
  
  def destroy
    @user_session = UserSession.find
    @user_session.destroy
    
    redirect_to root_url, notice: 'Successfully logged out.'
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index  
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url, notice: 'Registration successful.'
    else
      render :new
    end
  end
  
  def edit
    @user = current_user
  end
  
  def update
    @user = current_user

    if @user.update_attributes(user_params)
      redirect_to root_url, notice: 'Successfully updated profile.'
    else
      render :edit
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Al4</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

    <div id="container">
	<div id="user_nav">
	   <% if current_user %>
	     <%= link_to "Edit profile", edit_user_path(:current) %>
	     <%= link_to "Logout", logout_path %>
	   <% else %>
	     <%= link_to "Register", new_user_path %>
	     <%= link_to "Log in", login_path %>
	   <% end %>		
	</div>

      <%- flash.each do |name, msg| -%>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <%- end -%>

	  <%= yield %>	
	</div>

</body>
</html>

app/views/user_sessions/new.html.erb
<%= form_for @user_session do |form| %>

<% if @user_session.errors.any? %>
<div id="error_explanation">
	<ul>
		<% @user_session.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>

  <p>
    <%= form.label :username, "Username" %>
    <%= form.text_field :username %>
  </p>
  <p>
    <%= form.label :password, "Password" %>
    <%= form.password_field :password %>
  </p>
  <p>
    <%= form.submit "Submit" %>
  </p>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <p>
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p><%= f.submit "Submit" %></p>
<% end %>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
This is the users page.

app/views/users/new.html.erb
<% if @user.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@user.errors.count, "error") %> prohibited this photo from being saved:</h2>

	<ul>
		<% @user.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>
  
<%= render 'form' %>